/* ============================================================
   MOCK DATA — NOIR. E-Commerce
   ============================================================ */

const PRODUCTS = [
  {
    id: 1, slug: 'essential-oversized-tee',
    name: 'Essential Oversized Tee', brand: 'NOIR',
    category: 'tshirts', gender: 'unisex', collection: 'essentials',
    price: 59, comparePrice: null,
    isNew: false, isBestSeller: true, isLimited: false,
    badge: null, rating: 4.8, reviewCount: 124,
    stock: { XS:2, S:3, M:8, L:12, XL:6, XXL:2 },
    colors: [{ name:'Black', hex:'#0a0a0a' },{ name:'White', hex:'#f0ebe2' },{ name:'Ash', hex:'#888' }],
    ph: 'ph-1',
    description: 'O silhuete que define a coleção. Cortado em jersey de 380gsm, o Essential Tee assenta largo nos ombros com uma bainha descida que cria proporções perfeitas.',
    details: ['380gsm heavyweight jersey','100% Algodão Orgânico','Fit oversized','Ombros descidos','Colarinho canelado','Lavagem: 30°C suave'],
    sizes: ['XS','S','M','L','XL','XXL'],
    tags: ['bestseller','essential'],
  },
  {
    id: 2, slug: 'void-heavyweight-hoodie',
    name: 'Void Heavyweight Hoodie', brand: 'NOIR',
    category: 'hoodies', gender: 'unisex', collection: 'essentials',
    price: 129, comparePrice: null,
    isNew: true, isBestSeller: true, isLimited: false,
    badge: 'New', rating: 4.9, reviewCount: 87,
    stock: { S:1, M:5, L:9, XL:4, XXL:0 },
    colors: [{ name:'Black', hex:'#0a0a0a' },{ name:'Charcoal', hex:'#333' }],
    ph: 'ph-2',
    description: 'Construído para durar. O Void Hoodie é feito em fleece de algodão de 580gsm, com capuz duplo estruturado e costuras de alta resistência.',
    details: ['580gsm brushed fleece','100% Algodão','Capuz duplo estruturado','Bolso canguru reforçado','Punhos e bainha canelados','Lavagem: 30°C inverter'],
    sizes: ['S','M','L','XL','XXL'],
    tags: ['new','bestseller'],
  },
  {
    id: 3, slug: 'wide-leg-cargo-pants',
    name: 'Wide Leg Cargo Pants', brand: 'NOIR',
    category: 'pants', gender: 'men', collection: 'new-season',
    price: 149, comparePrice: 189,
    isNew: true, isBestSeller: false, isLimited: false,
    badge: 'Sale', rating: 4.7, reviewCount: 43,
    stock: { 28:3, 30:6, 32:4, 34:2, 36:1 },
    colors: [{ name:'Black', hex:'#0a0a0a' },{ name:'Olive', hex:'#4a4a2a' },{ name:'Stone', hex:'#c8b89a' }],
    ph: 'ph-3',
    description: 'Silhuete amplo inspirado no workwear utilitário. Seis bolsos funcionais, cintura ajustável e queda perfeita sobre sneakers.',
    details: ['98% Algodão, 2% Elastano','Seis bolsos','Cintura ajustável','Fit wide leg','Comprimento regular','Lavagem: 30°C'],
    sizes: ['28','30','32','34','36'],
    tags: ['new','sale'],
  },
  {
    id: 4, slug: 'arc-longsleeve',
    name: 'Arc Longsleeve', brand: 'NOIR',
    category: 'tshirts', gender: 'unisex', collection: 'essentials',
    price: 79, comparePrice: null,
    isNew: false, isBestSeller: false, isLimited: false,
    badge: null, rating: 4.6, reviewCount: 58,
    stock: { XS:5, S:8, M:12, L:10, XL:7, XXL:3 },
    colors: [{ name:'Black', hex:'#0a0a0a' },{ name:'Navy', hex:'#0f1a2e' },{ name:'Cream', hex:'#f0e8d6' }],
    ph: 'ph-4',
    description: 'Construção premium de manga comprida em jersey 320gsm. Costuras flatlock visíveis para um detalhe técnico subtil.',
    details: ['320gsm jersey','100% Algodão Orgânico','Fit slightly oversized','Costuras flatlock','Punhos canelados','Lavagem: 30°C'],
    sizes: ['XS','S','M','L','XL','XXL'],
    tags: ['essential'],
  },
  {
    id: 5, slug: 'noir-track-jacket',
    name: 'Track Jacket', brand: 'NOIR',
    category: 'outerwear', gender: 'unisex', collection: 'new-season',
    price: 189, comparePrice: null,
    isNew: true, isBestSeller: false, isLimited: true,
    badge: 'Limited', rating: 5.0, reviewCount: 29,
    stock: { S:2, M:3, L:2, XL:1, XXL:0 },
    colors: [{ name:'Black', hex:'#0a0a0a' },{ name:'White', hex:'#f0ebe2' }],
    ph: 'ph-5',
    description: 'Edição limitada. O Track Jacket revisita o clássico dos anos 90 em nylon técnico impermeável com detalhes bordados a mão.',
    details: ['100% Nylon técnico','Impermeável DWR','Bordado a mão','Forro em mesh','Dois bolsos com fecho','Lavagem: a seco'],
    sizes: ['S','M','L','XL','XXL'],
    tags: ['new','limited'],
  },
  {
    id: 6, slug: 'structured-cap',
    name: 'Structured Cap', brand: 'NOIR',
    category: 'accessories', gender: 'unisex', collection: 'essentials',
    price: 49, comparePrice: null,
    isNew: false, isBestSeller: true, isLimited: false,
    badge: null, rating: 4.7, reviewCount: 91,
    stock: { 'One Size': 20 },
    colors: [{ name:'Black', hex:'#0a0a0a' },{ name:'White', hex:'#f0ebe2' },{ name:'Khaki', hex:'#8a7a5a' }],
    ph: 'ph-6',
    description: 'Estruturado. Limpo. Intemporal. O Structured Cap em twill de algodão premium com bordado tonal a baixo perfil.',
    details: ['100% Twill de algodão','Bordado tonal','6 painéis estruturados','Fecho traseiro ajustável','Pala curva'],
    sizes: ['One Size'],
    tags: ['bestseller','essential'],
  },
  {
    id: 7, slug: 'oversized-coach-jacket',
    name: 'Oversized Coach Jacket', brand: 'NOIR',
    category: 'outerwear', gender: 'unisex', collection: 'new-season',
    price: 229, comparePrice: null,
    isNew: true, isBestSeller: false, isLimited: false,
    badge: 'New', rating: 4.8, reviewCount: 19,
    stock: { S:4, M:6, L:5, XL:3, XXL:1 },
    colors: [{ name:'Black', hex:'#0a0a0a' },{ name:'Stone', hex:'#c8b89a' }],
    ph: 'ph-7',
    description: 'Coach jacket reimaginada com fit oversized e detalhes premium. Shell em ripstop de algodão resistente, forro acetinado.',
    details: ['Shell: 100% Ripstop cotton','Forro: 100% Viscose','Fit oversized','Peito e bolsos laterais','Fecho zip principal','Lavagem: 30°C suave'],
    sizes: ['S','M','L','XL','XXL'],
    tags: ['new'],
  },
  {
    id: 8, slug: 'utility-shorts',
    name: 'Utility Shorts', brand: 'NOIR',
    category: 'pants', gender: 'men', collection: 'summer-drop',
    price: 89, comparePrice: null,
    isNew: false, isBestSeller: true, isLimited: false,
    badge: null, rating: 4.5, reviewCount: 62,
    stock: { 28:5, 30:8, 32:7, 34:4, 36:2 },
    colors: [{ name:'Black', hex:'#0a0a0a' },{ name:'Olive', hex:'#4a4a2a' }],
    ph: 'ph-8',
    description: 'Shorts utilitários em sarja pesada com quatro bolsos cargo. Comprimento a meio da coxa para proporções ideais.',
    details: ['100% Sarja de algodão 280gsm','Quatro bolsos cargo','Cintura ajustável','Comprimento mid-thigh','Lavagem: 30°C'],
    sizes: ['28','30','32','34','36'],
    tags: ['bestseller'],
  },
  {
    id: 9, slug: 'relaxed-chino',
    name: 'Relaxed Chino', brand: 'NOIR',
    category: 'pants', gender: 'men', collection: 'essentials',
    price: 119, comparePrice: null,
    isNew: false, isBestSeller: false, isLimited: false,
    badge: null, rating: 4.6, reviewCount: 37,
    stock: { 28:2, 30:5, 32:8, 34:6, 36:3 },
    colors: [{ name:'Khaki', hex:'#8a7a5a' },{ name:'Black', hex:'#0a0a0a' },{ name:'Navy', hex:'#0f1a2e' }],
    ph: 'ph-1',
    description: 'Chino relaxed em sarja de algodão peach-finish. O equilíbrio perfeito entre elegante e casual.',
    details: ['100% Sarja de algodão peach-finish','Fit relaxed','Quatro bolsos','Lavagem: 30°C'],
    sizes: ['28','30','32','34','36'],
    tags: ['essential'],
  },
  {
    id: 10, slug: 'logo-beanie',
    name: 'Logo Beanie', brand: 'NOIR',
    category: 'accessories', gender: 'unisex', collection: 'essentials',
    price: 35, comparePrice: null,
    isNew: false, isBestSeller: true, isLimited: false,
    badge: null, rating: 4.9, reviewCount: 148,
    stock: { 'One Size': 35 },
    colors: [{ name:'Black', hex:'#0a0a0a' },{ name:'Charcoal', hex:'#333' },{ name:'Cream', hex:'#f0e8d6' }],
    ph: 'ph-2',
    description: 'Gorro em malha dupla de lã merino com patch de marca bordado. Quente, suave, intemporal.',
    details: ['100% Lã Merino','Malha dupla','Patch bordado','One Size'],
    sizes: ['One Size'],
    tags: ['bestseller','essential'],
  },
  {
    id: 11, slug: 'graphic-tee-arch',
    name: 'Arch Graphic Tee', brand: 'NOIR',
    category: 'tshirts', gender: 'unisex', collection: 'new-season',
    price: 69, comparePrice: null,
    isNew: true, isBestSeller: false, isLimited: false,
    badge: 'New', rating: 4.7, reviewCount: 33,
    stock: { XS:3, S:6, M:9, L:7, XL:4, XXL:1 },
    colors: [{ name:'Black', hex:'#0a0a0a' },{ name:'White', hex:'#f0ebe2' }],
    ph: 'ph-3',
    description: 'Gráfico exclusivo impresso em jersey orgânico de alta gramagem. Tinta a base de água com acabamento matte premium.',
    details: ['350gsm jersey orgânico','Tinta à base de água','Impressão DTG','Fit oversized','Lavagem: 30°C inverter'],
    sizes: ['XS','S','M','L','XL','XXL'],
    tags: ['new'],
  },
  {
    id: 12, slug: 'minimal-tote-bag',
    name: 'Minimal Tote Bag', brand: 'NOIR',
    category: 'accessories', gender: 'unisex', collection: 'essentials',
    price: 45, comparePrice: null,
    isNew: false, isBestSeller: false, isLimited: false,
    badge: null, rating: 4.6, reviewCount: 55,
    stock: { 'One Size': 18 },
    colors: [{ name:'Black', hex:'#0a0a0a' },{ name:'Natural', hex:'#d4c4a0' }],
    ph: 'ph-4',
    description: 'Tote em canvas de algodão 12oz com alças reforçadas e interior forrado. Espaçoso, durável, minimalista.',
    details: ['100% Canvas de algodão 12oz','Interior forrado','Alças reforçadas','Medidas: 42×38×12cm'],
    sizes: ['One Size'],
    tags: ['essential'],
  },
  {
    id: 13, slug: 'quarter-zip-fleece',
    name: 'Quarter Zip Fleece', brand: 'NOIR',
    category: 'hoodies', gender: 'unisex', collection: 'new-season',
    price: 109, comparePrice: null,
    isNew: true, isBestSeller: false, isLimited: false,
    badge: 'New', rating: 4.8, reviewCount: 21,
    stock: { S:5, M:7, L:6, XL:3 },
    colors: [{ name:'Black', hex:'#0a0a0a' },{ name:'Mocha', hex:'#5a3a2a' }],
    ph: 'ph-5',
    description: 'Polar quarter-zip em microfleece de alto loft. Leve, quente e com acabamento premium em cada detalhe.',
    details: ['100% Poliéster reciclado','Microfleece high-loft','Zip YKK','Bolso lateral com zip','Fit regular'],
    sizes: ['S','M','L','XL'],
    tags: ['new'],
  },
  {
    id: 14, slug: 'washed-denim-jacket',
    name: 'Washed Denim Jacket', brand: 'NOIR',
    category: 'outerwear', gender: 'unisex', collection: 'new-season',
    price: 179, comparePrice: 219,
    isNew: false, isBestSeller: false, isLimited: false,
    badge: 'Sale', rating: 4.5, reviewCount: 28,
    stock: { S:3, M:4, L:5, XL:2 },
    colors: [{ name:'Indigo', hex:'#1a2a4a' },{ name:'Black Wash', hex:'#1a1a1a' }],
    ph: 'ph-6',
    description: 'Clássico reinventado. Denim de 12oz com lavagem stone-wash premium para um aspeto desgastado autêntico.',
    details: ['100% Denim de algodão 12oz','Stone-wash premium','Fit slightly oversized','Botões de latão','Dois bolsos peito + dois laterais','Lavagem: 30°C inverter'],
    sizes: ['S','M','L','XL'],
    tags: ['sale'],
  },
  {
    id: 15, slug: 'women-crop-hoodie',
    name: 'Crop Hoodie', brand: 'NOIR',
    category: 'hoodies', gender: 'women', collection: 'new-season',
    price: 99, comparePrice: null,
    isNew: true, isBestSeller: true, isLimited: false,
    badge: 'New', rating: 4.9, reviewCount: 64,
    stock: { XS:4, S:6, M:8, L:5, XL:2 },
    colors: [{ name:'Black', hex:'#0a0a0a' },{ name:'Cream', hex:'#f0e8d6' },{ name:'Pink', hex:'#d4a0a0' }],
    ph: 'ph-7',
    description: 'Hoodie cropped em fleece premium 400gsm. Fit feminino com drop shoulder e acabamentos ultra-suaves.',
    details: ['400gsm fleece orgânico','Drop shoulder','Comprimento cropped','Colarinho canelado','Bolso canguru','Lavagem: 30°C'],
    sizes: ['XS','S','M','L','XL'],
    tags: ['new','bestseller'],
  },
  {
    id: 16, slug: 'women-wide-leg-trousers',
    name: 'Wide Leg Trousers', brand: 'NOIR',
    category: 'pants', gender: 'women', collection: 'new-season',
    price: 129, comparePrice: null,
    isNew: true, isBestSeller: false, isLimited: false,
    badge: 'New', rating: 4.7, reviewCount: 31,
    stock: { XS:3, S:5, M:7, L:4, XL:2 },
    colors: [{ name:'Black', hex:'#0a0a0a' },{ name:'Cream', hex:'#f0e8d6' }],
    ph: 'ph-8',
    description: 'Calças wide-leg de corte fluido em gabardine de alta torção. Cintura elástica para conforto máximo.',
    details: ['100% Gabardine','Cintura elástica','Fit wide-leg fluido','Bolsos laterais','Lavagem: 30°C suave'],
    sizes: ['XS','S','M','L','XL'],
    tags: ['new'],
  },
];

const COLLECTIONS = [
  { id: 'new-season',  name: 'New Season',       count: 8,  ph: 'ph-1' },
  { id: 'essentials',  name: 'Essentials',        count: 12, ph: 'ph-3' },
  { id: 'summer-drop', name: 'Summer Drop',       count: 6,  ph: 'ph-5' },
  { id: 'limited',     name: 'Limited Edition',   count: 4,  ph: 'ph-7' },
];

const CATEGORIES = [
  { id: 'tshirts',     label: 'T-Shirts & Tops' },
  { id: 'hoodies',     label: 'Hoodies & Fleece' },
  { id: 'pants',       label: 'Calças & Shorts' },
  { id: 'outerwear',   label: 'Casacos' },
  { id: 'accessories', label: 'Acessórios' },
];

const REVIEWS = [
  { id:1, name:'Miguel F.', rating:5, date:'14 Mai 2026', verified:true, product:'Essential Oversized Tee', text:'Qualidade incrível. O peso do tecido é perfeito, não é demasiado pesado nem leve. Já lavei várias vezes e mantém a forma.' },
  { id:2, name:'Ana R.', rating:5, date:'10 Mai 2026', verified:true, product:'Void Heavyweight Hoodie', text:'O melhor hoodie que já tive. O fleece é incrivelmente suave e o fit oversized é exatamente o que queria. Vale cada cêntimo.' },
  { id:3, name:'João C.', rating:4, date:'08 Mai 2026', verified:true, product:'Wide Leg Cargo Pants', text:'Ótima qualidade de construção. Os bolsos são funcionais. Tirei uma estrela só porque o tamanho veste um bocado grande.' },
  { id:4, name:'Sara M.', rating:5, date:'05 Mai 2026', verified:true, product:'Structured Cap', text:'Perfeita. Estruturada mas não demasiado rígida. O bordado é muito limpo. Comprei em três cores.' },
  { id:5, name:'Diogo L.', rating:5, date:'01 Mai 2026', verified:true, product:'Track Jacket', text:'Edição limitada e dá para perceber porquê. Acabamentos perfeitos, o nylon é de alta qualidade. Uma peça de coleção.' },
  { id:6, name:'Inês P.', rating:5, date:'28 Abr 2026', verified:true, product:'Crop Hoodie', text:'Finalmente um hoodie feito a pensar em mulheres. O fit é perfeito, o tecido é premium. Super recomendo.' },
];

const BENEFITS = [
  { icon: 'truck',    title: 'Envio Grátis',        sub: 'Em encomendas acima de €80' },
  { icon: 'refresh',  title: 'Devoluções Gratuitas', sub: '30 dias para devolver' },
  { icon: 'shield',   title: 'Pagamento Seguro',     sub: 'SSL encriptado' },
  { icon: 'headset',  title: 'Suporte 24/7',         sub: 'Sempre disponíveis' },
];
