/* ============================================================
   MOCK DATA — Camisolas de Futebol
   ============================================================ */

const PRODUCTS = [
  /* ---- CABO VERDE ---- */
  {
    id: 1, slug: 'cabo-verde-principal',
    name: 'Cabo Verde — Camisola Principal', brand: 'Tubarões Azuis',
    category: 'selecoes', gender: 'unisex', collection: 'cabo-verde',
    price: 79, comparePrice: null,
    isNew: true, isBestSeller: true, isLimited: false,
    badge: 'New', rating: 4.9, reviewCount: 87,
    stock: { S:4, M:8, L:10, XL:6, XXL:2 },
    colors: [{ name:'Azul', hex:'#003893' }],
    img: 'assets/images/cv-jersey-blue.svg',
    ph: 'ph-cv-blue',
    description: 'A camisola oficial da Seleção Nacional de Cabo Verde para a temporada 2025/26. Tecido técnico de alta performance com 10 estrelas representando as 10 ilhas do arquipélago.',
    details: ['Tecido técnico DryFit 100% Poliéster','Corte regular fit','10 estrelas bordadas','Lavagem: 30°C à mão','Produto oficial'],
    sizes: ['S','M','L','XL','XXL'],
    tags: ['selecao','africa','cabo-verde','new','bestseller'],
  },
  {
    id: 2, slug: 'cabo-verde-alternativa',
    name: 'Cabo Verde — Camisola Alternativa', brand: 'Tubarões Azuis',
    category: 'selecoes', gender: 'unisex', collection: 'cabo-verde',
    price: 79, comparePrice: null,
    isNew: true, isBestSeller: true, isLimited: false,
    badge: 'New', rating: 4.8, reviewCount: 62,
    stock: { S:3, M:7, L:9, XL:5, XXL:1 },
    colors: [{ name:'Branco', hex:'#FFFFFF' }],
    img: 'assets/images/cv-jersey-white.svg',
    ph: 'ph-cv-white',
    description: 'A camisola alternativa da Seleção de Cabo Verde. Design branco com detalhes azuis e a banda das cores nacionais. Perfeita para os jogos fora.',
    details: ['Tecido técnico DryFit 100% Poliéster','Corte regular fit','Detalhes em azul nacional','10 estrelas bordadas','Lavagem: 30°C à mão'],
    sizes: ['S','M','L','XL','XXL'],
    tags: ['selecao','africa','cabo-verde','new','bestseller'],
  },

  /* ---- SELEÇÕES EUROPEIAS ---- */
  {
    id: 3, slug: 'portugal-principal',
    name: 'Portugal — Camisola Principal', brand: 'FPF',
    category: 'selecoes', gender: 'unisex', collection: 'selecoes',
    price: 89, comparePrice: null,
    isNew: true, isBestSeller: true, isLimited: false,
    badge: 'New', rating: 4.9, reviewCount: 214,
    stock: { S:5, M:10, L:12, XL:8, XXL:3 },
    colors: [{ name:'Vermelho', hex:'#A2173A' },{ name:'Verde', hex:'#006600' }],
    ph: 'ph-portugal',
    description: 'A camisola oficial da Seleção Nacional de Portugal para a temporada 2025/26. Vermelho profundo com detalhes a verde e o escudo bordado.',
    details: ['Tecido técnico Nike DRI-FIT ADV','100% Poliéster reciclado','Tecnologia Aeroswift','Escudo bordado','Lavagem: 30°C'],
    sizes: ['S','M','L','XL','XXL'],
    tags: ['selecao','europa','portugal','new','bestseller'],
  },
  {
    id: 4, slug: 'franca-principal',
    name: 'França — Camisola Principal', brand: 'FFF',
    category: 'selecoes', gender: 'unisex', collection: 'selecoes',
    price: 89, comparePrice: null,
    isNew: false, isBestSeller: true, isLimited: false,
    badge: null, rating: 4.8, reviewCount: 178,
    stock: { S:6, M:9, L:11, XL:7, XXL:2 },
    colors: [{ name:'Azul', hex:'#002776' }],
    ph: 'ph-france',
    description: 'Les Bleus. A camisola da campeã do mundo em azul profundo com a galinha gaulesa bordada. Elegância e performance em cada detalhe.',
    details: ['Tecido técnico Nike DRI-FIT','100% Poliéster','Gola canelada','Escudo bordado','Lavagem: 30°C'],
    sizes: ['S','M','L','XL','XXL'],
    tags: ['selecao','europa','franca','bestseller'],
  },
  {
    id: 5, slug: 'alemanha-principal',
    name: 'Alemanha — Camisola Principal', brand: 'DFB',
    category: 'selecoes', gender: 'unisex', collection: 'selecoes',
    price: 85, comparePrice: null,
    isNew: false, isBestSeller: false, isLimited: false,
    badge: null, rating: 4.7, reviewCount: 93,
    stock: { S:5, M:8, L:10, XL:6, XXL:2 },
    colors: [{ name:'Branco', hex:'#FFFFFF' },{ name:'Preto', hex:'#0a0a0a' }],
    ph: 'ph-germany',
    description: 'Die Mannschaft. Branca imaculada com as três listras pretas e o escudo da águia alemã. Clássico intemporal do futebol mundial.',
    details: ['Tecido técnico Adidas HEAT.RDY','100% Poliéster reciclado','Corte atlético','Escudo bordado','Lavagem: 30°C'],
    sizes: ['S','M','L','XL','XXL'],
    tags: ['selecao','europa','alemanha'],
  },
  {
    id: 6, slug: 'italia-principal',
    name: 'Itália — Camisola Principal', brand: 'FIGC',
    category: 'selecoes', gender: 'unisex', collection: 'selecoes',
    price: 85, comparePrice: null,
    isNew: false, isBestSeller: false, isLimited: false,
    badge: null, rating: 4.7, reviewCount: 71,
    stock: { S:4, M:7, L:9, XL:5, XXL:1 },
    colors: [{ name:'Azul', hex:'#003399' }],
    ph: 'ph-italy',
    description: 'Gli Azzurri. O icónico azul da Azzurra com o escudo FIGC bordado. Campeões do mundo e do estilo.',
    details: ['Tecido técnico Adidas','100% Poliéster','Corte regular','Escudo bordado','Lavagem: 30°C'],
    sizes: ['S','M','L','XL','XXL'],
    tags: ['selecao','europa','italia'],
  },
  {
    id: 7, slug: 'espanha-principal',
    name: 'Espanha — Camisola Principal', brand: 'RFEF',
    category: 'selecoes', gender: 'unisex', collection: 'selecoes',
    price: 89, comparePrice: null,
    isNew: true, isBestSeller: false, isLimited: false,
    badge: 'New', rating: 4.8, reviewCount: 55,
    stock: { S:5, M:9, L:10, XL:6, XXL:2 },
    colors: [{ name:'Vermelho', hex:'#AA151B' },{ name:'Amarelo', hex:'#F1BF00' }],
    ph: 'ph-espanha',
    description: 'La Roja. A camisola da atual campeã europeia e mundial. Vermelho vibrante com os detalhes dourados reais.',
    details: ['Tecido técnico Adidas','100% Poliéster reciclado','Corte slim fit','Escudo bordado','Lavagem: 30°C'],
    sizes: ['S','M','L','XL','XXL'],
    tags: ['selecao','europa','espanha','new'],
  },

  /* ---- SELEÇÕES MUNDIAIS ---- */
  {
    id: 8, slug: 'brasil-principal',
    name: 'Brasil — Camisola Principal', brand: 'CBF',
    category: 'selecoes', gender: 'unisex', collection: 'selecoes',
    price: 89, comparePrice: null,
    isNew: false, isBestSeller: true, isLimited: false,
    badge: null, rating: 5.0, reviewCount: 302,
    stock: { S:8, M:15, L:18, XL:10, XXL:4 },
    colors: [{ name:'Amarelo', hex:'#F5D100' },{ name:'Verde', hex:'#009C3B' }],
    ph: 'ph-brasil',
    description: 'A Seleção Canarinha. O amarelo mais famoso do futebol com o verde e o escudo da CBF. Cinco estrelas, cinco mundiais.',
    details: ['Tecido técnico Nike DRI-FIT','100% Poliéster reciclado','Corte regular fit','5 estrelas bordadas','Lavagem: 30°C'],
    sizes: ['S','M','L','XL','XXL'],
    tags: ['selecao','america','brasil','bestseller'],
  },
  {
    id: 9, slug: 'argentina-principal',
    name: 'Argentina — Camisola Principal', brand: 'AFA',
    category: 'selecoes', gender: 'unisex', collection: 'selecoes',
    price: 89, comparePrice: null,
    isNew: false, isBestSeller: true, isLimited: false,
    badge: null, rating: 4.9, reviewCount: 241,
    stock: { S:6, M:12, L:15, XL:9, XXL:3 },
    colors: [{ name:'Azul Celeste', hex:'#74ACDF' },{ name:'Branco', hex:'#FFFFFF' }],
    ph: 'ph-argentina',
    description: 'Albiceleste campeã do mundo. As listras celeste e branca que conquistaram o Qatar 2022. A camisola do Lionel Messi.',
    details: ['Tecido técnico Adidas HEAT.RDY','100% Poliéster reciclado','Listras clássicas','3 estrelas bordadas','Lavagem: 30°C'],
    sizes: ['S','M','L','XL','XXL'],
    tags: ['selecao','america','argentina','bestseller'],
  },

  /* ---- GRANDES CLUBES ---- */
  {
    id: 10, slug: 'barcelona-principal',
    name: 'FC Barcelona — Camisola Principal', brand: 'FC Barcelona',
    category: 'clubes', gender: 'unisex', collection: 'clubes',
    price: 95, comparePrice: null,
    isNew: false, isBestSeller: true, isLimited: false,
    badge: null, rating: 4.9, reviewCount: 318,
    stock: { S:5, M:10, L:12, XL:7, XXL:3 },
    colors: [{ name:'Blaugrana', hex:'#A50044' }],
    ph: 'ph-barca',
    description: 'Blaugrana. As icónicas listras verticais azuis e vermelhas do clube mais titulado do mundo. Més que un club.',
    details: ['Tecido técnico Nike DRI-FIT','100% Poliéster reciclado','Listras verticais clássicas','Escudo bordado','Lavagem: 30°C'],
    sizes: ['S','M','L','XL','XXL'],
    tags: ['clube','espanha','barcelona','bestseller'],
  },
  {
    id: 11, slug: 'real-madrid-principal',
    name: 'Real Madrid — Camisola Principal', brand: 'Real Madrid',
    category: 'clubes', gender: 'unisex', collection: 'clubes',
    price: 95, comparePrice: null,
    isNew: false, isBestSeller: true, isLimited: false,
    badge: null, rating: 4.8, reviewCount: 276,
    stock: { S:6, M:11, L:13, XL:8, XXL:3 },
    colors: [{ name:'Branco', hex:'#FAFAFA' }],
    ph: 'ph-madrid',
    description: 'Los Blancos. O branco imaculado do maior clube do mundo. 15 Ligas dos Campeões. Hala Madrid.',
    details: ['Tecido técnico Adidas HEAT.RDY','100% Poliéster reciclado','Corte slim atlético','Escudo bordado','Lavagem: 30°C'],
    sizes: ['S','M','L','XL','XXL'],
    tags: ['clube','espanha','real-madrid','bestseller'],
  },
  {
    id: 12, slug: 'manchester-united-principal',
    name: 'Manchester United — Camisola Principal', brand: 'Man United',
    category: 'clubes', gender: 'unisex', collection: 'clubes',
    price: 95, comparePrice: 115,
    isNew: false, isBestSeller: false, isLimited: false,
    badge: 'Sale', rating: 4.7, reviewCount: 134,
    stock: { S:4, M:8, L:9, XL:5, XXL:2 },
    colors: [{ name:'Vermelho', hex:'#DA020E' }],
    ph: 'ph-manu',
    description: 'Red Devils. O vermelho lendário de Old Trafford com o diabo bordado. Teatro dos Sonhos.',
    details: ['Tecido técnico Adidas','100% Poliéster','Gola polo clássica','Escudo bordado','Lavagem: 30°C'],
    sizes: ['S','M','L','XL','XXL'],
    tags: ['clube','inglaterra','man-united','sale'],
  },
  {
    id: 13, slug: 'psg-principal',
    name: 'PSG — Camisola Principal', brand: 'Paris Saint-Germain',
    category: 'clubes', gender: 'unisex', collection: 'clubes',
    price: 99, comparePrice: null,
    isNew: true, isBestSeller: false, isLimited: true,
    badge: 'Limited', rating: 4.9, reviewCount: 88,
    stock: { S:2, M:4, L:5, XL:3, XXL:1 },
    colors: [{ name:'Azul', hex:'#003C8E' },{ name:'Vermelho', hex:'#ED1C24' }],
    ph: 'ph-psg',
    description: 'Ici c'est Paris. A camisola do Paris Saint-Germain em edição limitada. Azul de Paris com detalhes vermelhos e a Torre Eiffel bordada.',
    details: ['Tecido técnico Nike DRI-FIT ADV','100% Poliéster reciclado','Aeroswift technology','Torre Eiffel bordada','Lavagem: 30°C'],
    sizes: ['S','M','L','XL','XXL'],
    tags: ['clube','franca','psg','limited','new'],
  },
  {
    id: 14, slug: 'liverpool-principal',
    name: 'Liverpool — Camisola Principal', brand: 'Liverpool FC',
    category: 'clubes', gender: 'unisex', collection: 'clubes',
    price: 95, comparePrice: null,
    isNew: false, isBestSeller: false, isLimited: false,
    badge: null, rating: 4.7, reviewCount: 112,
    stock: { S:5, M:9, L:10, XL:6, XXL:2 },
    colors: [{ name:'Vermelho', hex:'#C8102E' }],
    ph: 'ph-liverpool',
    description: 'You'll Never Walk Alone. O vermelho de Anfield, lar dos Reds mais famosos de Inglaterra.',
    details: ['Tecido técnico Nike DRI-FIT','100% Poliéster reciclado','Corte slim fit','Liver bird bordado','Lavagem: 30°C'],
    sizes: ['S','M','L','XL','XXL'],
    tags: ['clube','inglaterra','liverpool'],
  },
  {
    id: 15, slug: 'ac-milan-principal',
    name: 'AC Milan — Camisola Principal', brand: 'AC Milan',
    category: 'clubes', gender: 'unisex', collection: 'clubes',
    price: 92, comparePrice: null,
    isNew: true, isBestSeller: false, isLimited: false,
    badge: 'New', rating: 4.8, reviewCount: 67,
    stock: { S:4, M:7, L:9, XL:5, XXL:1 },
    colors: [{ name:'Vermelho', hex:'#FB090B' },{ name:'Preto', hex:'#0a0a0a' }],
    ph: 'ph-milan',
    description: 'Forza Milan. As listras verticais vermelho e preto do clube mais titulado de Milão. Sete Ligas dos Campeões.',
    details: ['Tecido técnico Puma','100% Poliéster','Listras clássicas verticais','Escudo bordado','Lavagem: 30°C'],
    sizes: ['S','M','L','XL','XXL'],
    tags: ['clube','italia','milan','new'],
  },
  {
    id: 16, slug: 'manchester-city-principal',
    name: 'Manchester City — Camisola Principal', brand: 'Man City',
    category: 'clubes', gender: 'unisex', collection: 'clubes',
    price: 95, comparePrice: null,
    isNew: false, isBestSeller: false, isLimited: false,
    badge: null, rating: 4.7, reviewCount: 94,
    stock: { S:5, M:8, L:11, XL:6, XXL:2 },
    colors: [{ name:'Azul Celeste', hex:'#6CABDD' }],
    ph: 'ph-city',
    description: 'Sky Blues. O azul celeste de Manchester, triplo campeão europeu. O emblema do futebol moderno.',
    details: ['Tecido técnico Puma ULTRAWEAVE','100% Poliéster reciclado','Corte atlético','Escudo bordado','Lavagem: 30°C'],
    sizes: ['S','M','L','XL','XXL'],
    tags: ['clube','inglaterra','man-city'],
  },
];

const COLLECTIONS = [
  { id: 'cabo-verde',  name: 'Cabo Verde — Casa',       count: 1,  img: 'assets/images/cv-jersey-blue.svg' },
  { id: 'cabo-verde',  name: 'Cabo Verde — Alternativa', count: 1,  img: 'assets/images/cv-jersey-white.svg' },
  { id: 'selecoes',    name: 'Seleções Mundiais',        count: 8,  ph: 'ph-brasil' },
  { id: 'clubes',      name: 'Grandes Clubes',           count: 8,  ph: 'ph-barca' },
];

const CATEGORIES = [
  { id: 'selecoes', label: 'Seleções Nacionais' },
  { id: 'clubes',   label: 'Clubes' },
];

const REVIEWS = [
  { id:1, name:'Tiago F.', rating:5, date:'12 Mai 2026', verified:true, product:'Cabo Verde — Camisola Principal', text:'Qualidade incrível. Recebi em 3 dias e a camisola é mesmo fiel à foto. Orgulho caboverdiano no peito!' },
  { id:2, name:'Ana R.', rating:5, date:'10 Mai 2026', verified:true, product:'Portugal — Camisola Principal', text:'A melhor camisola de Portugal que já tive. O tecido é muito suave, o vermelho é muito vivo. Já lavei várias vezes e mantém a cor.' },
  { id:3, name:'João C.', rating:4, date:'08 Mai 2026', verified:true, product:'FC Barcelona — Camisola Principal', text:'Ótima qualidade. As listras blaugrana estão perfeitas. Comprei para o meu filho e ele não tira.' },
  { id:4, name:'Sara M.', rating:5, date:'05 Mai 2026', verified:true, product:'Brasil — Camisola Principal', text:'Perfeita. O amarelo canarinho é exatamente como nas fotos. Usei no jogo e recebi muitos elogios.' },
  { id:5, name:'Carlos L.', rating:5, date:'01 Mai 2026', verified:true, product:'PSG — Camisola Principal', text:'Edição limitada e nota-se porquê. Acabamentos de luxo, o tecido é de alta qualidade. Chegou bem embalada.' },
  { id:6, name:'Inês P.', rating:5, date:'28 Abr 2026', verified:true, product:'Cabo Verde — Camisola Alternativa', text:'A camisola branca é lindíssima. Os detalhes azuis e as estrelas estão perfeitos. Muito orgulho!' },
];

const BENEFITS = [
  { icon: 'truck',    title: 'Envio Grátis',        sub: 'Em encomendas acima de €80' },
  { icon: 'refresh',  title: 'Devoluções Gratuitas', sub: '30 dias para devolver' },
  { icon: 'shield',   title: 'Pagamento Seguro',     sub: 'SSL encriptado' },
  { icon: 'headset',  title: 'Suporte 24/7',         sub: 'Sempre disponíveis' },
];
